In [33]:
from os import listdir
from os.path import isfile, join
import pandas as pd
import numpy as np

In [36]:
# can vary :
epochs = 800
replicas = 15
sets = 50

df = pd.DataFrame()
params = np.array([[1,2,.5,.5]])
batch = 0
line = 0
for hyperparams in params:
    for setno in range(sets):
        for repititions in range(4):
            cfg = pd.DataFrame(np.reshape(hyperparams,(1,4)), columns = ['alpha', 'gamma', 'rho', 'sigma'])
            cfg['set'] = setno
            cfg['epochs'] = epochs
            cfg['replicas'] = replicas
            cfg['line'] = line
            cfg['batch'] = batch
            line = line + 1
            df = df.append(cfg)
        batch = batch + 1

In [39]:
df

    alpha  gamma  rho  sigma  set  epochs  replicas  line  batch
0     1.0    2.0  0.5    0.5    0     800        15     0      0
0     1.0    2.0  0.5    0.5    0     800        15     1      0
0     1.0    2.0  0.5    0.5    0     800        15     2      0
0     1.0    2.0  0.5    0.5    0     800        15     3      0
0     1.0    2.0  0.5    0.5    1     800        15     4      1
..    ...    ...  ...    ...  ...     ...       ...   ...    ...
0     1.0    2.0  0.5    0.5   48     800        15   195     48
0     1.0    2.0  0.5    0.5   49     800        15   196     49
0     1.0    2.0  0.5    0.5   49     800        15   197     49
0     1.0    2.0  0.5    0.5   49     800        15   198     49
0     1.0    2.0  0.5    0.5   49     800        15   199     49

[200 rows x 9 columns]

In [38]:
df.to_csv('configs.csv')

In [5]:
np.array([1:2])

SyntaxError: invalid syntax (<ipython-input-5-228de1a6d85d>, line 1)