In [1]:
from os import listdir
from os.path import isfile, join
import pandas as pd
import numpy as np

In [2]:
# can vary :
epochs = 150
replicas = 125
sets = 100

df = pd.DataFrame()
params = np.array([[1,2,.5,.5]])
batch = 0
line = 0
for hyperparams in params:
    for setno in range(sets):
        for repititions in range(4):
            cfg = pd.DataFrame(np.reshape(hyperparams,(1,4)), columns = ['alpha', 'gamma', 'rho', 'sigma'])
            cfg['set'] = setno
            cfg['epochs'] = epochs
            cfg['replicas'] = replicas
            cfg['line'] = line
            cfg['batch'] = batch
            line = line + 1
            df = df.append(cfg)
        batch = batch + 1

In [3]:
df

    alpha  gamma  rho  sigma  set  epochs  replicas  line  batch
0     1.0    2.0  0.5    0.5    0     150       125     0      0
0     1.0    2.0  0.5    0.5    0     150       125     1      0
0     1.0    2.0  0.5    0.5    0     150       125     2      0
0     1.0    2.0  0.5    0.5    0     150       125     3      0
0     1.0    2.0  0.5    0.5    1     150       125     4      1
..    ...    ...  ...    ...  ...     ...       ...   ...    ...
0     1.0    2.0  0.5    0.5   98     150       125   395     98
0     1.0    2.0  0.5    0.5   99     150       125   396     99
0     1.0    2.0  0.5    0.5   99     150       125   397     99
0     1.0    2.0  0.5    0.5   99     150       125   398     99
0     1.0    2.0  0.5    0.5   99     150       125   399     99

[400 rows x 9 columns]

In [4]:
df.to_csv('configs2.csv')

In [5]:
np.array([1:2])

SyntaxError: invalid syntax (<ipython-input-5-228de1a6d85d>, line 1)